name: Eleventy Build

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        python-version: [3.11]

    steps:
        - uses: actions/checkout@v3

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}

        - name: Use Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}

        - name: Ensure latest pip
          run: pip install --upgrade pip

        - name: Install Python 
          run: npm run install-python

        - name: Check VENV
          run: echo "VIRTUAL ENV:" $VIRTUAL_ENV

        - name: Install dependencies 
          run: npm ci

        - name: Build
          run: npm run build-ghpages

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            publish_dir: ./_site